FROM mcr.microsoft.com/dotnet/sdk:8.0 as build
WORKDIR /src
COPY ./DockerNETCoreApp.csproj ./
RUN dotnet restore "DockerNETCoreApp.csproj"
COPY . .
RUN dotnet publish ./DockerNETCoreApp.csproj -c Release -o /app/

FROM mcr.microsoft.com/dotnet/sdk:8.0 as final
WORKDIR /app
COPY --from=build /app .
ENTRYPOINT [ "dotnet", "DockerNETCoreApp.dll" ]